<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>78c833e5-b435-445d-9526-75f610f31492</elementGuidId>
    <imagePath></imagePath>
    <name>button_payFullBalance</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/form[1]/div[4]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Pay Full Balance\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>px-4 py-2 bg-white/5 hover:bg-white/10 rounded-full text-[10px] font-black uppercase tracking-widest text-slate-400 transition-all border border-transparent hover:border-white/5</value>
        <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>PAY FULL BALANCE</value>
        <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
    </webElementProperties>
</WebElementEntity>