analytics.onpremise.enable=true
onpremise.email="kevin.jackey@katalon.com"
onpremise.password="H0Q291REJi8UR6urf6TZjgva7BVaQM0n"
analytics.onpremise.organization="{\\"accountId\\"\:1509469,\\"accountUuid\\"\:\\"a79ec54e-d6e5-40e3-9fa8-e8bf2af20691\\",\\"id\\"\:2154983,\\"name\\"\:\\"Katalian Bank\\",\\"role\\"\:\\"USER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false}"
analytics.onpremise.server="https\://testops.katalon.io"
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 3033951,\\n  \\"name\\"\: \\"Katalian Banking 2.0\\",\\n  \\"teamId\\"\: 3005943,\\n  \\"organizationId\\"\: 2154967,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3005943\\n}"
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=true
