analytics.account={"id"\:1509469,"name"\:"TestOps Demo","uuid"\:"a79ec54e-d6e5-40e3-9fa8-e8bf2af20691","domain"\:"gia-g3-demo"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization=null
analytics.onpremise.server=https\://testops.katalon.io
analytics.project={"id"\:3033951,"name"\:"Katalian Banking 2.0","teamId"\:3005943,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:2154967,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3005943,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
onpremise.email=kevin.jackey@katalon.com
onpremise.password=H0Q291REJi8UR6urf6TZjgva7BVaQM0n
