analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3033951,"name"\:"Katalian Banking 2.0","teamId"\:3005943,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:2154967,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:3005943,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=false
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
