import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.model.FailureHandling
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject

/**
 * Test Case: Net Liquidity label is visible on the dashboard after login
 * Generated by test-compiler-service. Do not edit manually.
 * Compilation ID: d4e3f596-9c09-46b8-8c78-62d106143a7b
 */

// Open browser
WebUI.openBrowser('https://katalian-banking.vercel.app/login')

// Step: Navigate to login page
// ⚠ LOW_CONFIDENCE alignment (0.00): verify that the selector below matches the step description before relying on this test

// Step: Enter username
// Type "bankinguser123" into "enter_username"
// Note: WebUI.setText uses sendKeys — if this input does not respond (React/Vue app), replace with executeJavaScript to set value directly
WebUI.setText(findTestObject('Object Repository/August TestOps Demo Generated Script/enter_username'), 'bankinguser123')

// Step: Enter password
// Type "<<secret:vault:Katalian_Banking_Password>>" into "enter_password"
// Note: WebUI.setText uses sendKeys — if this input does not respond (React/Vue app), replace with executeJavaScript to set value directly
WebUI.setText(findTestObject('Object Repository/August TestOps Demo Generated Script/enter_password'), '<<secret:vault:Katalian_Banking_Password>>')

// Step: Click Enter Vault Access button
// Click "click_enter_vault_access_button"
WebUI.scrollToElement(findTestObject('Object Repository/August TestOps Demo Generated Script/click_enter_vault_access_button'), 30)
WebUI.click(findTestObject('Object Repository/August TestOps Demo Generated Script/click_enter_vault_access_button'))

// Close browser
WebUI.closeBrowser()
