<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>select_transferFrom</name>
   <tag></tag>
   <elementGuidId>19e182fc-16f9-49fb-8def-93d355bf93f3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'block w-full px-3 py-2 bg-gray-800 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm text-white' and @id = 'depositFromAccountId' and @name = 'depositFromAccountId' and (text() = 'New funds
        Checking (...7890)
        Savings (...1234)' or . = 'New funds
        Checking (...7890)
        Savings (...1234)')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[2]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=\&quot;Transfer from\&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-3 py-2 bg-gray-800 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm text-white</value>
      <webElementGuid>279eee3d-cb58-4e8c-8cf2-1bfed750f98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>depositFromAccountId</value>
      <webElementGuid>51d1e2b2-8489-4150-bb00-0d9d1c78a637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>depositFromAccountId</value>
      <webElementGuid>883c43b0-7afb-4323-adc1-32d1a00f6bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New funds
        Checking (...7890)
        Savings (...1234)</value>
      <webElementGuid>08bd4850-0641-4bbd-b63c-4e33702960c3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
