<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_depositAuthorization</name>
   <tag></tag>
   <elementGuidId>a7a763d0-af34-4224-9e21-1ea2566b96ce</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[3]/div[2]/div[2]/button[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> internal:text=\&quot;${button_depositAuthorization_ButtonInternalText_1}\&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative inline-flex items-center justify-center font-bold py-3 px-6 rounded-2xl transition-all duration-300 active:scale-[0.98] disabled:opacity-30 disabled:cursor-not-allowed text-sm overflow-hidden bg-emerald-500 hover:bg-emerald-400 text-slate-950 shadow-[0_10px_20px_rgba({{ip_address}})]  !rounded-full px-10</value>
      <webElementGuid>a61b41c9-4bdb-43ed-86b4-704f85678d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>9ecedb01-e121-4724-8846-e2fdccae26be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>daa338d2-dc61-4656-bdbe-244e98a5969f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
