<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>99b24c95-55b7-4d1f-9503-70c7c882d7a8</elementGuidId>
    <imagePath></imagePath>
    <name>select_recipientFacility</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/form[1]/div[3]/div[1]/select[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Recipient Facility\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>block w-full px-4 py-4 bg-slate-950 border border-white/5 rounded-2xl shadow-inner focus:outline-none focus:border-emerald-500/50 focus:ring-4 focus:ring-emerald-500/5 transition-all text-sm text-white font-medium appearance-none</value>
        <webElementGuid>b0f012b9-a3be-4fa8-9e81-4a3e50abd25a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>toAccount</value>
        <webElementGuid>b0f012b9-a3be-4fa8-9e81-4a3e50abd25a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Select facility...
        Checking (...7890) — $5,345.54
        Savings (...1234) — $104,456.67
        Credit Card (...{{credit_debit_number}}) — $1,250.00</value>
        <webElementGuid>b0f012b9-a3be-4fa8-9e81-4a3e50abd25a</webElementGuid>
    </webElementProperties>
</WebElementEntity>