<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_fraudReporting</name>
   <tag></tag>
   <elementGuidId>bc6a7841-d030-4d5b-a2ae-817ab31972d4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/section[1]/div[1]/button[3]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> internal:has-text=/^\ud83d\udee1\ufe0fFraud Reporting$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex items-center justify-between p-5 bg-white/5 rounded-2xl hover:bg-white/10 transition-all group border border-transparent hover:border-white/5</value>
      <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>🛡️
        Fraud Reporting</value>
      <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
