<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6ad97b1c-57a9-4dcb-958b-facc4f8860b6</elementGuidId>
    <imagePath></imagePath>
    <name>p_insufficientFunds</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/form[1]/p[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>p</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>text-center text-red-400 bg-red-900/50 p-3 rounded-lg</value>
        <webElementGuid>2bca8b96-046e-4e81-9df1-35540f0a699f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Insufficient funds for this transfer.</value>
        <webElementGuid>2bca8b96-046e-4e81-9df1-35540f0a699f</webElementGuid>
    </webElementProperties>
</WebElementEntity>