<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>select_fromAccount</name>
   <tag></tag>
   <elementGuidId>52b7ccc0-094c-4e20-8f34-b14afa5196e4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'mt-1 block w-full pl-3 pr-10 py-2 bg-gray-800 border border-gray-600 rounded-md focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm text-white' and @id = 'fromAccount' and (text() = 'Select an account
        Checking (...7890) - Balance: $5345.54
        Savings (...1234) - Balance: $104456.67' or . = 'Select an account
        Checking (...7890) - Balance: $5345.54
        Savings (...1234) - Balance: $104456.67')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/form[1]/div[1]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=\&quot;From\&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 block w-full pl-3 pr-10 py-2 bg-gray-800 border border-gray-600 rounded-md focus:outline-none focus:ring-teal-500 focus:border-teal-500 sm:text-sm text-white</value>
      <webElementGuid>dfa5ede6-943d-44e6-a641-db9b68891145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromAccount</value>
      <webElementGuid>5c712487-e366-4bd8-804c-44b6fa9ed72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an account
        Checking (...7890) - Balance: $5345.54
        Savings (...1234) - Balance: $104456.67</value>
      <webElementGuid>eed590dc-ae0e-41c3-af23-726cdb56b60e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
