<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_savings</name>
   <tag></tag>
   <elementGuidId>2849bad9-494d-4be9-9798-986606f8d22f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button >> internal:text=\&quot;\ud83d\udcb0Savings\&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-slate-900/40 border border-white/5 p-6 rounded-3xl text-center hover:bg-emerald-500/10 hover:border-emerald-500/20 transition-all group</value>
      <webElementGuid>10e74973-24c3-4b81-a047-2b53ed03b731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>💰
        
        SAVINGS</value>
      <webElementGuid>10e74973-24c3-4b81-a047-2b53ed03b731</webElementGuid>
   </webElementProperties>
</WebElementEntity>
