<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a8012139-f83c-4299-9cf2-b595635aa887</elementGuidId>
    <imagePath></imagePath>
    <name>button_freezeAllCards</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/section[1]/div[1]/button[2]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:has-text=/^\u2744\ufe0fFreeze All Cards$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>w-full flex items-center justify-between p-5 bg-white/5 rounded-2xl hover:bg-white/10 transition-all group border border-transparent hover:border-white/5</value>
        <webElementGuid>10e74973-24c3-4b81-a047-2b53ed03b731</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>❄️
        Freeze All Cards</value>
        <webElementGuid>10e74973-24c3-4b81-a047-2b53ed03b731</webElementGuid>
    </webElementProperties>
</WebElementEntity>