<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b9744153-2f91-4e4b-9051-c5b9fca04e52</elementGuidId>
    <imagePath></imagePath>
    <name>div_captureFront</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.aspect-\\[1\\.8\\/1\\] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>aspect-[1.8/1] rounded-3xl border-2 border-dashed flex flex-col items-center justify-center cursor-pointer transition-all overflow-hidden relative group border-white/10 bg-slate-950 hover:border-white/20</value>
        <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>📸
        CAPTURE FRONT</value>
        <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
    </webElementProperties>
</WebElementEntity>