<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c9f30ba7-50a2-480f-a125-ac54c2bad252</elementGuidId>
    <imagePath></imagePath>
    <name>button_submit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[2]/form[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>form button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>p-4 bg-emerald-500 text-slate-950 rounded-2xl hover:bg-emerald-400 transition-all active:scale-95 shadow-lg</value>
        <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>96ee89e7-beee-4942-bcf9-f3cdb76fd87e</webElementGuid>
    </webElementProperties>
</WebElementEntity>